// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/image.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AsciiArtServiceClient is the client API for AsciiArtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsciiArtServiceClient interface {
	GetImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error)
}

type asciiArtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsciiArtServiceClient(cc grpc.ClientConnInterface) AsciiArtServiceClient {
	return &asciiArtServiceClient{cc}
}

func (c *asciiArtServiceClient) GetImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error) {
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, "/proto.AsciiArtService/GetImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsciiArtServiceServer is the server API for AsciiArtService service.
// All implementations must embed UnimplementedAsciiArtServiceServer
// for forward compatibility
type AsciiArtServiceServer interface {
	GetImage(context.Context, *ImageRequest) (*ImageResponse, error)
	mustEmbedUnimplementedAsciiArtServiceServer()
}

// UnimplementedAsciiArtServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAsciiArtServiceServer struct {
}

func (UnimplementedAsciiArtServiceServer) GetImage(context.Context, *ImageRequest) (*ImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedAsciiArtServiceServer) mustEmbedUnimplementedAsciiArtServiceServer() {}

// UnsafeAsciiArtServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsciiArtServiceServer will
// result in compilation errors.
type UnsafeAsciiArtServiceServer interface {
	mustEmbedUnimplementedAsciiArtServiceServer()
}

func RegisterAsciiArtServiceServer(s grpc.ServiceRegistrar, srv AsciiArtServiceServer) {
	s.RegisterService(&AsciiArtService_ServiceDesc, srv)
}

func _AsciiArtService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsciiArtServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AsciiArtService/GetImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsciiArtServiceServer).GetImage(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AsciiArtService_ServiceDesc is the grpc.ServiceDesc for AsciiArtService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsciiArtService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AsciiArtService",
	HandlerType: (*AsciiArtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetImage",
			Handler:    _AsciiArtService_GetImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/image.proto",
}
